### ISSUE TITLE
Add map support for the dump

### ISSUE THREAD

**Issue by Palbolsky** [NuriYuri/ts-marshal#2]

**Comment by NuriYuri** [comment]
Made a commit for that: https://github.com/NuriYuri/ts-marshal/commit/aaab5ff382b427843a763ab9f8371df4ce06d752

Basically you can use a Map<MarshalObject, MarshalObject> as input of dump and it'll dump as as a Hash. Note: you don't need the __class key, if you need extension or whatever you can. In general to check the object format refer to the tests (especially those that were added :))
